### ISSUE TITLE
drupal approved pagination

### ISSUE THREAD

**Issue by AtRiskMedia** [d34dman/drupal-jsonapi-params#40]
Hi, thanks so much for this amazing library!

The drupal docs are very clear: "If you take only one thing away from this guide, it should be that **you should not construct your own pagination URLs**", https://www.drupal.org/docs/core-modules-and-themes/core-modules/jsonapi-module/pagination

I see there's a module to allow override: https://www.drupal.org/project/jsonapi_page_limit but i'm hoping to avoid this

Is there any way to access the "links" next and count on the response from Drupal?
I'd like to run successive fetches in a recursive loop but could only do this using .addPageOffset

Is there a better pattern to follow?

**Comment by AtRiskMedia** [comment]
What i've got so far is use this library to construct the first query, e.g. get all article nodes

And on the first fetch i intercept the response. If the links.next.href is present, i'll loop and then combine all the data and return the full payload.

**Comment by d34dman** [comment]
@AtRiskMedia am glad that you found this module helpful and thanks for sharing your concern regarding pagination.

ATM, the module only provide a helper method generate your query. It is independent of result. It works with no Feedback. Keeping it independent of how the actual query is executed (fetch, axios, XMLHttpRequest...) helps keep it framework agnostic. 

If we have to continue on this, then to get dynamic `next` links based on results, we would have to feed the current result into `DrupalJsonApiParams` and call some method like `next` get the url , fire the query, get the result feed it back to `DrupalJsonApiParams` and repeat ... I don't think it as a nice developer experience over what you have achieved in your sample code.

What you have done is a really a nice pattern to follow none the less. Alternatively, we can add this to project documentation (in README.md) so that people can benefit from this.

What do you think?
